export const keysEn = [
  { code: 'Backquote', key: '`' },
  { code: 'Digit1', key: '1' },
  { code: 'Digit2', key: '2' },
  { code: 'Digit3', key: '3' },
  { code: 'Digit4', key: '4' },
  { code: 'Digit5', key: '5' },
  { code: 'Digit6', key: '6' },
  { code: 'Digit7', key: '7' },
  { code: 'Digit8', key: '8' },
  { code: 'Digit9', key: '9' },
  { code: 'Digit0', key: '0' },
  { code: 'Minus', key: '-' },
  { code: 'Equal', key: '=' },
  { code: 'Backspace', key: 'backspace' },
  { code: 'Tab', key: 'tab' },
  { code: 'KeyQ', key: 'q' },
  { code: 'KeyW', key: 'w' },
  { code: 'KeyE', key: 'e' },
  { code: 'KeyR', key: 'r' },
  { code: 'KeyT', key: 't' },
  { code: 'KeyY', key: 'y' },
  { code: 'KeyU', key: 'u' },
  { code: 'KeyI', key: 'i' },
  { code: 'KeyO', key: 'o' },
  { code: 'KeyP', key: 'p' },
  { code: 'BracketLeft', key: '[' },
  { code: 'BracketRight', key: ']' },
  { code: 'Delete', key: 'del' },
  { code: 'CapsLock', key: 'caps' },
  { code: 'KeyA', key: 'a' },
  { code: 'KeyS', key: 's' },
  { code: 'KeyD', key: 'd' },
  { code: 'KeyF', key: 'f' },
  { code: 'KeyG', key: 'g' },
  { code: 'KeyH', key: 'h' },
  { code: 'KeyJ', key: 'j' },
  { code: 'KeyK', key: 'k' },
  { code: 'KeyL', key: 'l' },
  { code: 'Semicolon', key: ';' },
  { code: 'Quote', key: "'" },
  { code: 'Enter', key: 'enter' },
  { code: 'ShiftLeft', key: 'shiftLeft' },
  { code: 'KeyZ', key: 'z' },
  { code: 'KeyX', key: 'x' },
  { code: 'KeyC', key: 'c' },
  { code: 'KeyV', key: 'v' },
  { code: 'KeyB', key: 'b' },
  { code: 'KeyN', key: 'n' },
  { code: 'KeyM', key: 'm' },
  { code: 'Comma', key: ',' },
  { code: 'Period', key: '.' },
  { code: 'Slash', key: '/' },
  { code: 'ArrowUp', key: '▲' },
  { code: 'ShiftRight', key: 'shiftRight' },
  { code: 'ControlLeft', key: 'ctrlLeft' },
  { code: 'MetaLeft', key: 'win' },
  { code: 'AltLeft', key: 'altLeft' },
  { code: 'Space', key: 'space' },
  { code: 'AltRight', key: 'altRight' },
  { code: 'ArrowLeft', key: '◄' },
  { code: 'ArrowDown', key: '▼' },
  { code: 'ArrowRight', key: '►' },
  { code: 'ControlRight', key: 'ctrlRight' },
];

export const keysRu = [
  { code: 'Backquote', key: 'ё' },
  { code: 'Digit1', key: '1' },
  { code: 'Digit2', key: '2' },
  { code: 'Digit3', key: '3' },
  { code: 'Digit4', key: '4' },
  { code: 'Digit5', key: '5' },
  { code: 'Digit6', key: '6' },
  { code: 'Digit7', key: '7' },
  { code: 'Digit8', key: '8' },
  { code: 'Digit9', key: '9' },
  { code: 'Digit0', key: '0' },
  { code: 'Minus', key: '-' },
  { code: 'Equal', key: '=' },
  { code: 'Backspace', key: 'backspace' },
  { code: 'Tab', key: 'tab' },
  { code: 'KeyQ', key: 'й' },
  { code: 'KeyW', key: 'ц' },
  { code: 'KeyE', key: 'у' },
  { code: 'KeyR', key: 'к' },
  { code: 'KeyT', key: 'е' },
  { code: 'KeyY', key: 'н' },
  { code: 'KeyU', key: 'г' },
  { code: 'KeyI', key: 'ш' },
  { code: 'KeyO', key: 'щ' },
  { code: 'KeyP', key: 'з' },
  { code: 'BracketLeft', key: 'х' },
  { code: 'BracketRight', key: 'ъ' },
  { code: 'Delete', key: 'del' },
  { code: 'CapsLock', key: 'caps' },
  { code: 'KeyA', key: 'ф' },
  { code: 'KeyS', key: 'ы' },
  { code: 'KeyD', key: 'в' },
  { code: 'KeyF', key: 'а' },
  { code: 'KeyG', key: 'п' },
  { code: 'KeyH', key: 'р' },
  { code: 'KeyJ', key: 'о' },
  { code: 'KeyK', key: 'л' },
  { code: 'KeyL', key: 'д' },
  { code: 'Semicolon', key: 'ж' },
  { code: 'Quote', key: 'э' },
  { code: 'Enter', key: 'enter' },
  { code: 'ShiftLeft', key: 'shiftLeft' },
  { code: 'KeyZ', key: 'я' },
  { code: 'KeyX', key: 'ч' },
  { code: 'KeyC', key: 'с' },
  { code: 'KeyV', key: 'м' },
  { code: 'KeyB', key: 'и' },
  { code: 'KeyN', key: 'т' },
  { code: 'KeyM', key: 'ь' },
  { code: 'Comma', key: 'б' },
  { code: 'Period', key: 'ю' },
  { code: 'Slash', key: '.' },
  { code: 'ArrowUp', key: '▲' },
  { code: 'ShiftRight', key: 'shiftRight' },
  { code: 'ControlLeft', key: 'ctrlLeft' },
  { code: 'MetaLeft', key: 'win' },
  { code: 'AltLeft', key: 'altLeft' },
  { code: 'Space', key: 'space' },
  { code: 'AltRight', key: 'altRight' },
  { code: 'ArrowLeft', key: '◄' },
  { code: 'ArrowDown', key: '▼' },
  { code: 'ArrowRight', key: '►' },
  { code: 'ControlRight', key: 'ctrlRight' },
];

export const shiftedKeys = {
  en: {
    '`': '~',
    1: '!',
    2: '@',
    3: '#',
    4: '$',
    5: '%',
    6: '^',
    7: '&',
    8: '*',
    9: '(',
    0: ')',
    '-': '_',
    '=': '+',
    '[': '{',
    ']': '}',
    ';': ':',
    "'": '"',
    ',': '<',
    '.': '>',
    '/': '?',
  },
  ru: {
    1: '!',
    2: '"',
    3: '№',
    4: ';',
    5: '%',
    6: ':',
    7: '?',
    8: '*',
    9: '(',
    0: ')',
    '-': '_',
    '=': '+',
    '.': ',',
  },
};

export const shiftedKeysReversed = {
  en: Object.fromEntries(
    Object.entries(shiftedKeys.en).map(([key, value]) => [value, key]),
  ),
  ru: Object.fromEntries(
    Object.entries(shiftedKeys.ru).map(([key, value]) => [value, key]),
  ),
};
